// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'description': string;
  'iconWrapper': string;
  'image': string;
  'info': string;
  'modal': string;
  'modalCard': string;
  'modal_open': string;
  'price': string;
  'rating': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
