// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'closeIcon': string;
  'iconContainer': string;
  'link': string;
  'link_desktop': string;
  'listDesktop': string;
  'listWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
