// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'filter': string;
  'filterPanels': string;
  'filterPanels_desktop': string;
  'filterPanels_open': string;
  'iconWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
