// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'currency': string;
  'iconContainer': string;
  'image': string;
  'lineContainer': string;
  'price': string;
  'rating': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
