// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkboxTheme': string;
  'slider': string;
  'toggleTheme': string;
}
export const cssExports: CssExports;
export default cssExports;
