// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'container_bottom': string;
  'container_filter': string;
  'container_top': string;
  'header': string;
  'layout': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
